2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_setup.py:_flush():76] Current SDK version is 0.17.6
2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_setup.py:_flush():76] Configure stats pid to 1061799
2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_setup.py:_flush():76] Loading settings from /home/yyang-infobai/.config/wandb/settings
2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_setup.py:_flush():76] Loading settings from /home/yyang-infobai/AVDC_whl/flowdiffusion/wandb/settings
2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'flowdiffusion/pretrain.py', 'program_abspath': '/home/yyang-infobai/AVDC_whl/flowdiffusion/pretrain.py', 'program': '/home/yyang-infobai/AVDC_whl/flowdiffusion/pretrain.py'}
2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_init.py:_log_setup():521] Logging user logs to /home/yyang-infobai/AVDC_whl/flowdiffusion/wandb/run-20241127_150236-bqglt27g/logs/debug.log
2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_init.py:_log_setup():522] Logging internal logs to /home/yyang-infobai/AVDC_whl/flowdiffusion/wandb/run-20241127_150236-bqglt27g/logs/debug-internal.log
2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_init.py:init():559] calling init triggers
2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_init.py:init():566] wandb.init called with sweep_config: {}
config: {'wandb': {'wandb_project': 'AVDC_change_pretrain', 'wandb_entity': 'whl23333-tsinghua-university', 'run_name': 'faucetopen_fs12'}, 'save_path': '../results12/pretrain', 'gpt_save_path': '../results12/gpt', 'seed': 42, 'sample_per_seq': 8, 'valid_n': 1, 'batch_size': 64, 'train_steps': 5000, 'device': 'cuda', 'vqvae': {'action_window_size': 7, 'act_dim': 4, 'n_latent_dims': 512, 'vqvae_n_embed': 16, 'vqvae_groups': 2, 'act_scale': 10.0}, 'freeze': {'implicit_model': False, 'action_decoder': True, 'diffusion': False}, 'models': {'implicit_model': {'model_name': 'TwoStagePerceiverModel', 'params': {'num_freq_bands': 6, 'depth': 6, 'max_freq': 10.0, 'first_img_channels': 3, 'img_input_channels': 64, 'img_input_axis': 2, 'text_input_channels': 512, 'text_input_axis': 1, 'num_latents': 7, 'latent_dim': 16}}, 'action_decoder': {'model_name': 'VQDecoder', 'params': {'dir': '../decoder/pretrain/fancy-bush-10', 'device': 'cuda'}}, 'preprocess': {'model_name': 'Preprocess', 'params': {'hidden_dim': 16, 'act_len': 7, 'n_latent_dims': 512}}, 'diffusion_action_model': {'params': {'vq_dir': '/home/yyang-infobai/AVDC_whl/results12/pretrain/faucetopen_fsVar', 'load_vq': True, 'action_rate': 0.01}}}, 'trainer': {'results_folder': '../result_gpt5_frameskipVar_001_faucetopen_b6_s42/mw', 'train_batch_size': 6}, 'frameskip': 12, 'dataset': '/home/yyang-infobai/tasks_datasets/metaworld_faucetopen'}
2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_init.py:init():609] starting backend
2024-11-27 15:02:36,342 INFO    MainThread:1061799 [wandb_init.py:init():613] setting up manager
2024-11-27 15:02:36,347 INFO    MainThread:1061799 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-11-27 15:02:36,349 INFO    MainThread:1061799 [wandb_init.py:init():621] backend started and connected
2024-11-27 15:02:36,358 INFO    MainThread:1061799 [wandb_init.py:init():716] updated telemetry
2024-11-27 15:02:36,379 INFO    MainThread:1061799 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-11-27 15:04:06,394 ERROR   MainThread:1061799 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-11-27 15:04:06,394 ERROR   MainThread:1061799 [wandb_init.py:init():1187] error in wandb.init()
Traceback (most recent call last):
  File "/group/ycyang/anaconda3/envs/avdc/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1177, in init
    return wi.init()
  File "/group/ycyang/anaconda3/envs/avdc/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-11-27 15:04:07,416 WARNING MsgRouterThr:1061799 [router.py:message_loop():77] message_loop has been closed
