Preparing dataset...
Done





















































































































































































































































































































































































































































































































 39%|██████████████████████████████████▏                                                     | 1943/5000 [16:46<26:23,  1.93it/s]
Traceback (most recent call last):
  File "/home/yyang-infobai/AVDC_whl/flowdiffusion/pretrain.py", line 100, in <module>
    main(cfg)
  File "/home/yyang-infobai/AVDC_whl/flowdiffusion/pretrain.py", line 75, in main
    x, x_cond, goal, action = next(dl)
  File "/home/yyang-infobai/AVDC_whl/flowdiffusion/pretrain.py", line 24, in cycle
    for data in dl:
  File "/group/ycyang/anaconda3/envs/avdc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/group/ycyang/anaconda3/envs/avdc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "/group/ycyang/anaconda3/envs/avdc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1285, in _get_data
    success, data = self._try_get_data()
  File "/group/ycyang/anaconda3/envs/avdc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/group/ycyang/anaconda3/envs/avdc/lib/python3.9/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/group/ycyang/anaconda3/envs/avdc/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt